### ISSUE TITLE
MKTXP Stack - Everything Up but MKTXP

### ISSUE THREAD

**Issue by theaustinayers** [akpw/mktxp-stack#16]
Hello!

So looking into why I can't get MKTXP to work - this is on a Ubuntu 22.04.3 install. Fresh, clean install. User is non-sudo "mktxp" running this.

Upon running "docker logs mktxp" we can see:

`
----------------------------------------
Exception occurred during processing of request from ('172.18.0.5', 48524)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/socketserver.py", line 318, in _handle_request                                                                                         _noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.12/socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/local/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.12/http/server.py", line 424, in handle_one_reque                                                                                         st
    method()
  File "/usr/local/lib/python3.12/site-packages/prometheus_client/exposition.py"                                                                                         , line 329, in do_GET
    self.wfile.write(output)
  File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
`
When looking at :9090/targets?search= we can see that MKTXP is down with "Get "http://mktxp:49090/metrics": context deadline exceeded"

Not sure where to battle against this.

**Comment by theaustinayers** [comment]
While looking - Python 3.10 installs with Docker but 3.12 does not.
When installing 3.12 - this error now presents:
`
----------------------------------------
Exception occurred during processing of request from ('172.18.0.5', 48524)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.12/socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/local/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/usr/local/lib/python3.12/site-packages/prometheus_client/exposition.py", line 329, in do_GET
    self.wfile.write(output)
  File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('172.18.0.7', 47360)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.12/socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/local/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/usr/local/lib/python3.12/site-packages/prometheus_client/exposition.py", line 329, in do_GET
    self.wfile.write(output)
  File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
`

**Comment by akpw** [comment]
looks like a prometheus config issue, discussed e.g. [here](https://github.com/akpw/mktxp/issues/93)
